<a href="https://www.kaggle.com/code/alawdisoft/arabic-company-reviews?scriptVersionId=134252919" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/arabic-company-reviews/CompanyReviews.csv


In [2]:
df = pd.read_csv('/kaggle/input/arabic-company-reviews/CompanyReviews.csv')
df

Unnamed: 0                                 review_description  rating  \
0               0                                               رائع       1   
1               1  برنامج رائع جدا يساعد على تلبيه الاحتياجات بشك...       1   
2               2  التطبيق لا يغتح دائما بيعطيني لا يوجد اتصال با...      -1   
3               3                 لماذا لا يمكننا طلب من ماكدونالدز؟      -1   
4               4  البرنامج بيظهر كل المطاعم و مغلقه مع انها بتكو...      -1   
...           ...                                                ...     ...   
40041         128  تجربه جيده بس ينقصها عدم اهتمام خدمة العملاء ب...       0   
40042         129  انا ساكنة بمنطقة الكينج ولا توجد عربيات قبل ال...      -1   
40043         130  جيد ولكن لماذا لا توجد خطوط كثيره من المريوطيه...       0   
40044         131               جيدا جدا ...ولكن الاسعار عاليه جدا\n       0   
40045         132  التطبيق حلو جدا والخدمه ممتازه ولكن الاسعار عا...       0   

      company  
0      talbat  
1      talbat  
2      talbat  
3      talbat  
4      talbat  
...       ...  
40041    swvl  
40042    swvl  
40043    swvl  
40044    swvl  
40045    swvl  

[40046 rows x 4 columns]

In [3]:
df.isnull().sum()

Unnamed: 0            0
review_description    1
rating                0
company               0
dtype: int64

In [4]:
df.dropna(inplace=True)

In [5]:
from IPython.display import display , Markdown
for i in range(10):
    display(Markdown(" "+df['review_description'][i]))

 رائع

 برنامج رائع جدا يساعد على تلبيه الاحتياجات بشكل اسرع

 التطبيق لا يغتح دائما بيعطيني لا يوجد اتصال بالشبكة..مع انه النت عندي تمام شو الحل??

 لماذا لا يمكننا طلب من ماكدونالدز؟

 البرنامج بيظهر كل المطاعم و مغلقه مع انها بتكون فاتحه بقاله كده اكتر من شهر

 أصبح غالي جداً

 جميل جدا رائع. . .

 للأسف الواحد ينصدم بعد زيادة الاسعار و للاسف بعض المطاعم اصبحت معاملتهم رديئة

 برنامج توترز توصيل احلى من برنامجكم فاشل

 كتير في تحسن خدمة العملاء لطفين في بعض الاخطاء التقنية لكن بتصلحوها بسرعة وبعض التاخير سياسيتكم وتسويقكم صار افضل من كريم بالنسبة الي متفقين

In [6]:
df['rating'].value_counts()

 1    23921
-1    14199
 0     1925
Name: rating, dtype: int64

In [7]:
from sklearn.model_selection import train_test_split
X = df['review_description']
y = df['rating']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [8]:
y_train.value_counts() , y_test.value_counts() 

( 1    16124
 -1     9453
  0     1253
 Name: rating, dtype: int64,
  1    7797
 -1    4746
  0     672
 Name: rating, dtype: int64)

In [9]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC

text_clf_nb = Pipeline([('tfidf', TfidfVectorizer()),
                     ('clf', MultinomialNB()),])

text_clf_lsvc = Pipeline([('tfidf', TfidfVectorizer()),
                     ('clf', LinearSVC()),])

text_clf_nb.fit(X_train, y_train)


Pipeline(steps=[('tfidf', TfidfVectorizer()), ('clf', MultinomialNB())])

In [10]:
predictions = text_clf_nb.predict(X_test)

In [11]:
from sklearn import metrics
print(metrics.confusion_matrix(y_test,predictions))

[[3609    0 1137]
 [ 221    0  451]
 [ 526    0 7271]]


In [12]:
print(metrics.classification_report(y_test,predictions))

              precision    recall  f1-score   support

          -1       0.83      0.76      0.79      4746
           0       0.00      0.00      0.00       672
           1       0.82      0.93      0.87      7797

    accuracy                           0.82     13215
   macro avg       0.55      0.56      0.56     13215
weighted avg       0.78      0.82      0.80     13215



/opt/conda/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [13]:
print(metrics.accuracy_score(y_test,predictions))

0.8233068482784714


In [14]:
text_clf_lsvc.fit(X_train, y_train)

Pipeline(steps=[('tfidf', TfidfVectorizer()), ('clf', LinearSVC())])

In [15]:
print(metrics.confusion_matrix(y_test,predictions))

[[3609    0 1137]
 [ 221    0  451]
 [ 526    0 7271]]


In [16]:
print(metrics.classification_report(y_test,predictions))

              precision    recall  f1-score   support

          -1       0.83      0.76      0.79      4746
           0       0.00      0.00      0.00       672
           1       0.82      0.93      0.87      7797

    accuracy                           0.82     13215
   macro avg       0.55      0.56      0.56     13215
weighted avg       0.78      0.82      0.80     13215



/opt/conda/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [17]:
print(metrics.accuracy_score(y_test,predictions))

0.8233068482784714
